local image = {
  "⠀               ⢀⣀⣤⣤⣶⣶⣶⣶⣶⣶⣤⣄⣀           ",
  "⠀           ⢀⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣄       ",
  "⠀         ⠠⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣀    ",
  "⠀       ⣤⣶⣷⣶⣦⡀⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄  ",
  "⠀     ⣠⣿⣿⣿⣿⣿⣿⣿⣦⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷ ",
  "⠀    ⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿",
  "⠀  ⢀⡆⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢸⣿⠿⠛⠋⠉⠈⠈⠉⠛⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿",
  "⠀  ⣿⣿⠈⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠈            ⠛⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟",
  "⠀ ⣾⣿⣿⣷⠈⢿⣿⣿⣿⣿⣿⡿⠁                ⠙⣿⣿⣿⣿⣿⣿⠟ ",
  "⠀⢰⣿⣿⣿⣿⣿⣦⣀⠉⠉⠁⣀                    ⠈⠉⠉⠉   ",
  "⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠁                           ",
  "⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿                             ",
  "⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠀                            ",
  "⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⡅⠀                            ",
  "⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀                            ",
  "⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀                            ",
  "⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄                            ",
  "⠀⢹⣿⣿⣿⣿⣿⣿⠟⠛⠛⠛                            ",
  "⠀ ⣿⣿⣿⣿⠋⣤⣾⣿⣿⣿⣶⣄                  ⣴⣾⣿⣿⣷⣤  ",
  "⠀ ⠘⣿⣿ ⣾⣿⣿⣿⣿⣿⣿⣿⣷              ⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿ ",
  "⠀  ⠙⡇⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⢹⣦⣄       ⣀⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿",
  "⠀    ⢹⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿",
  "⠀     ⢿⣿⣿⣿⣿⣿⣿⣿⡿ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃",
  "⠀      ⠙⢿⣿⣿⣿⡿⠛⣀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁ ",
  "⠀         ⢀⣤⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠁   ",
  "⠀          ⠈⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠋      ",
  "⠀              ⠉⠛⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠟⠙⠁         ",
}

local function set_colors()
  vim.api.nvim_set_hl(0, "CTFL_Blue", { fg = "#1773EB" })
  vim.api.nvim_set_hl(0, "CTFL_Blue_2", { fg = "#1773EB" })
  vim.api.nvim_set_hl(0, "CTFL_Yellow", { fg = "#FFDA00" })
  vim.api.nvim_set_hl(0, "CTFL_Red", { fg = "#E44F20" })
  vim.api.nvim_set_hl(0, "CTFL_Red_2", { fg = "#E44F20" })
end

set_colors()

local header = {
  { string.sub(image[1], 1, 120), hl = "CTFL_Blue" },
  { "\n" },
  { string.sub(image[2], 1, 120), hl = "CTFL_Blue" },
  { "\n" },
  { string.sub(image[3], 1, 120), hl = "CTFL_Blue" },
  { "\n" },
  { string.sub(image[4], 1, 28), hl = "CTFL_Blue_2" },
  { string.sub(image[4], 29, 120), hl = "CTFL_Blue" },
  { "\n" },
  { string.sub(image[5], 1, 35), hl = "CTFL_Blue_2" },
  { string.sub(image[5], 36, 120), hl = "CTFL_Blue" },
  { "\n" },
  { string.sub(image[6], 1, 40), hl = "CTFL_Blue_2" },
  { string.sub(image[6], 41, 120), hl = "CTFL_Blue" },
  { "\n" },
  { string.sub(image[7], 1, 11), hl = "CTFL_Yellow" },
  { string.sub(image[7], 12, 44), hl = "CTFL_Blue_2" },
  { string.sub(image[7], 45, 120), hl = "CTFL_Blue" },
  { "\n" },
  { string.sub(image[8], 1, 11), hl = "CTFL_Yellow" },
  { string.sub(image[8], 12, 44), hl = "CTFL_Blue_2" },
  { string.sub(image[8], 45, 120), hl = "CTFL_Blue" },
  { "\n" },
  { string.sub(image[9], 1, 16), hl = "CTFL_Yellow" },
  { string.sub(image[9], 17, 43), hl = "CTFL_Blue_2" },
  { string.sub(image[9], 44, 120), hl = "CTFL_Blue" },
  { "\n" },
  { string.sub(image[10], 1, 27), hl = "CTFL_Yellow" },
  { string.sub(image[10], 28, 36), hl = "CTFL_Blue_2" },
  { string.sub(image[10], 37, 39), hl = "CTFL_Yellow" },
  { string.sub(image[10], 40, 120), hl = "CTFL_Blue" },
  { "\n" },
  { string.sub(image[11], 1, 120), hl = "CTFL_Yellow" },
  { "\n" },
  { string.sub(image[12], 1, 120), hl = "CTFL_Yellow" },
  { "\n" },
  { string.sub(image[13], 1, 120), hl = "CTFL_Yellow" },
  { "\n" },
  { string.sub(image[14], 1, 120), hl = "CTFL_Yellow" },
  { "\n" },
  { string.sub(image[15], 1, 120), hl = "CTFL_Yellow" },
  { "\n" },
  { string.sub(image[16], 1, 120), hl = "CTFL_Yellow" },
  { "\n" },
  { string.sub(image[17], 1, 120), hl = "CTFL_Yellow" },
  { "\n" },
  { string.sub(image[18], 1, 120), hl = "CTFL_Yellow" },
  { "\n" },
  { string.sub(image[19], 1, 19), hl = "CTFL_Yellow" },
  { string.sub(image[19], 20, 40), hl = "CTFL_Red_2" },
  { string.sub(image[19], 41, 120), hl = "CTFL_Red" },
  { "\n" },
  { string.sub(image[20], 1, 14), hl = "CTFL_Yellow" },
  { string.sub(image[20], 15, 41), hl = "CTFL_Red_2" },
  { string.sub(image[20], 42, 120), hl = "CTFL_Red" },
  { "\n" },
  { string.sub(image[21], 1, 11), hl = "CTFL_Yellow" },
  { string.sub(image[21], 12, 44), hl = "CTFL_Red_2" },
  { string.sub(image[21], 45, 120), hl = "CTFL_Red" },
  { "\n" },
  { string.sub(image[22], 1, 40), hl = "CTFL_Red_2" },
  { string.sub(image[22], 41, 120), hl = "CTFL_Red" },
  { "\n" },
  { string.sub(image[23], 1, 36), hl = "CTFL_Red_2" },
  { string.sub(image[23], 37, 120), hl = "CTFL_Red" },
  { "\n" },
  { string.sub(image[24], 1, 30), hl = "CTFL_Red_2" },
  { string.sub(image[24], 31, 120), hl = "CTFL_Red" },
  { "\n" },
  { string.sub(image[25], 1, 120), hl = "CTFL_Red" },
  { "\n" },
  { string.sub(image[26], 1, 120), hl = "CTFL_Red" },
  { "\n" },
  { string.sub(image[27], 1, 120), hl = "CTFL_Red" },
  { "\n" },
}

return {
  "snacks.nvim",
  opts = {
    dashboard = {
      sections = {
        { text = header, align = "center" },
        { section = "keys", gap = 1, padding = 1 },
        { section = "startup" },
      },
    },
  },
}
